### ISSUE TITLE
regarding solution 

### ISSUE THREAD

**Issue by INNFINITEMINDS** [ebatty/MathToolsforNeuroscience#6]
Respected madam ,

I am following the course .It is very nice .i have doubt regarding the tutorials - How can i know the answers of the tutorials ,in some  part i was unable to answer ,so can u provide the solution for reference purpose for all tutorials ?

Thank you for creating great content .

thanks
Arpit

**Comment by da5nsy** [comment]
Hi Ella,

I'm also working through the course currently, and was about to message you to ask whether there are solutions to the problems anywhere when I saw this issue. 

I recognise that if these aren't already written up that it would take some effort to do so, and so I would like to offer to assist if there is anything I could do to contribute.

(I really liked the way that NMA did it with 'Click for solution' links to the solutions at the bottom of each panel)

Thanks again for making the course available!

**Comment by da5nsy** [comment]
For other students: See https://compneuro.neuromatch.io/tutorials/W0D3_LinearAlgebra/chapter_title.html which has very similar material but with solutions.

**Comment by ebatty** [comment]
As I mentioned on twitter, I am happy to provide solutions if you email! I cannot release publicly as this is a course that students take for credit

**Comment by da5nsy** [comment]
Thank you @ebatty! I hadn't seen (and can't find) this on Twitter so the update here is much appreciated :)
I had wondered if that was the case.
